[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
numReplicas = 1

[[ports]]
port = "3000"
protocol = "http"
expose = true

[deploy.env]
NODE_ENV = "production"